### PR TITLE
Iss65

### PR DESCRIPTION
**Pull request by lsantuari**
I implemented the scripts for preprocessing the BAM files to map clipped sequences as split reads.

### CODE REVIEW

**Review by arnikz — CHANGES_REQUESTED** [review]
Please remove scheduler-specific directives and submit the script via xenon-cli instead.

**Review by arnikz — CHANGES_REQUESTED** [review]
Please integrate [`run_realign.sh`](https://github.com/GooglingTheCancerGenome/sv-channels/blob/iss65/scripts/utils/run_realign.sh) with the steps in [`run.sh`](https://github.com/GooglingTheCancerGenome/sv-channels/blob/dev/run.sh) so that the job submission code is kept at one place and all steps are tested in Travis CI.

**Comment by lsantuari** [comment]
@arnikz I am trying to keep a unique conda environment, but pysam and samtools are conflicting when I try to install them with conda. If I use two separate environment, I still find conflicts when trying to install the utils [enviroment](https://github.com/GooglingTheCancerGenome/sv-channels/pull/67/commits/b91aa2fd01c5754e49bdb8d6827260c14dadb339). Could you take a look at it?

**Comment by arnikz** [comment]
Populated one env - `sv-channels` and appended `utils` to it - but kept two separate `environment.yaml` files. The dependency issue seems resolved in c7e699f2260051e4845c3eab20415bc9daae1a5d but the CI fails because of another [issue](https://travis-ci.org/github/GooglingTheCancerGenome/sv-channels/jobs/724710048#L5185). @lsantuari could you check?

**Comment by lsantuari** [comment]
Mapping clipped sequences from the input BAM file using relaxed BWA mapping settings (-L 0,0) to recover additional split read positions worsens the performance of sv-channels.

**Pull request closed without merging**
