### PR TITLE
Implemented labeling modes

### PR DESCRIPTION
**Pull request by arnikz**
see #18

### CODE REVIEW

**Review by lsantuari — CHANGES_REQUESTED** [review]
`label_window_pairs_on_svcallset.json.gz` is saved in a strange folder structure at `labels_win200_` that recapitulates the absolute path. @arnikz Can you fix it?

**Comment by arnikz** [comment]
Do you expect this file in the same `labels_win200/22` dir as `label_window_pairs_on_split_read_positions.json.gz`?

**Comment by lsantuari** [comment]
Originally I was creating different folders for different label files. I guess it makes sense to keep the label files in a dir `labels` with a dir structure like `labels/window_length` as long as different label files can be tracked by sample name (it should be the name of the top folder) and window length. Even better, add this metadata in the JSON files too. Metadata should also include the name of the truth set used and of which candidate positions were used (split reads or sv callset for a certain caller). The chromosome name is not necessary, because the files contain labels for all the chromosomes in the chr list that you provide to the labelling script.

**Comment by arnikz** [comment]
For time being, the outdirs of both `label_*` scripts are set to `labels/win[len]`. Let's merge and normalize the outdirs of all channel scripts in a separate issue.

**Review by lsantuari — APPROVED** [review]

**Pull request merged**
